### ISSUE TITLE
tests/integration: warning with PyYAML.load 5.1

### ISSUE THREAD

**Issue by dilyanpalauzov** [tpm2-software/tpm2-tools#1420]
This code in test/integration/tests/activecredential.sh:
```python
# Capture the yaml output and verify that its the same as the name output
loaded_key_name_yaml=`python << pyscript
from __future__ import print_function
import yaml
with open('ak.out', 'r') as f:
    doc = yaml.load(f)
    print(doc['loaded-key']['name'])
pyscript`
```
complains on python 3.6 .7+ with PyYAML 5.1:
```
<stdin>:6: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/usr/local/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/local/lib/python3.6/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.6/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/usr/local/lib/python3.6/site-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.6/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib/python3.6/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "ak.out", line 38, column 11
loaded_key_name_yaml=`python << pyscript
from __future__ import print_function

import yaml

with open('ak.out', 'r') as f:
    doc = yaml.load(f)
    print(doc['loaded-key']['name'])
pyscript` on line 75 failed: 1
```

**Comment by dilyanpalauzov** [comment]
This warning is not issued with PyYAML 3.13 (last stable version before 5.1 according to https://pypi.org/project/PyYAML/#history).

**Comment by diabonas** [comment]
Interesting, I cannot reproduce this on my system (Arch Linux with a manually built python-yaml 5.1 package, since the package has not been updated in the official repositories): I get the warning
```
<stdin>:6: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
```
as well, but not the crash afterwards, so the test succeeds. What does the `ak.out` it fails to parse look like on your system?

Regardless of the test failure, `yaml.load(f)` should be changed to `yaml.load(f, Loader=yaml.SafeLoader)` (or equivalently `yaml.safe_load(f)`) according to the [warning message](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation).

**Comment by dilyanpalauzov** [comment]
I do not know what I did yesterday evening different, today I do not get this backtrace.  Perhaps the tests failed for different reason, today theypass.

Please use the occassion to get rid of the warning coming from `yaml.load()`.

**Comment by diabonas** [comment]
Glad you got it working! Regarding the warning, I have opened PR #1427.
