### ISSUE TITLE
Unable to create Object with tpm2_create - "out of memory for object contexts" (swtpm)

### ISSUE THREAD

**Issue by rkgfk** [tpm2-software/tpm2-tools#2960]
I try to create an object following the example here: [tpm2_create docs](https://tpm2-tools.readthedocs.io/en/latest/man/tpm2_create.1/)
The `tpm2_createprimary` command works as expected (i guess) but the `tpm2_create` command fails. Here's the trace:

```
[root@cbd4e0d71202 ~]# tpm2_createprimary -c primary.ctx
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
  raw: 0x30072
type:
  value: rsa
  raw: 0x1
exponent: 65537
bits: 2048
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: aes
  raw: 0x6
sym-mode:
  value: cfb
  raw: 0x43
sym-keybits: 128
rsa: dc27a9b86f50571c05d607a3c869b5d519cd67ea8b8297fa66c413246d000204eb182a4013b085a00b492a715cd792725839b8f3193d407fd835db5566dfd29f0ec8adc776043b5dccc4945f0541593c3e2c7a4255e7af8c63e34e6e1bf2ded2ebffdfb8296207e4ceadc61a312a608131c9478b694999645b46070730e0e346dc9b71da94d42e3d336ccfba739072bb4ae1f1505ada0003cb81c8bc894ef68c9be142e09bad1255298b0a360075637cb8ef72953b1cd0b94f71d11e54cd8ee12be97808a3d7abc935220627043bc03fb949fade09c36cbe3262a2982065a8a98d9d0e1de69af85881a1cc8aedb899c5d18ffcaf55ad430efee5880fd7ebf209
[root@cbd4e0d71202 ~]# tpm2_create -C primary.ctx -u obj.pub -r obj.priv
WARNING:esys:src/tss2-esys/api/Esys_ContextLoad.c:279:Esys_ContextLoad_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_ContextLoad.c:93:Esys_ContextLoad() Esys Finish ErrorCode (0x00000902) 
ERROR: Esys_ContextLoad(0x902) - tpm:warn(2.0): out of memory for object contexts
ERROR: Unable to run tpm2_create
[root@cbd4e0d71202 ~]# 
```
Am I doing something wrong?
I am using the software TPM2.0 swtpm in tpm2 mode inside a Fedora 35 Docker Container.

**Comment by williamcroberts** [comment]
Ahh no RM. Any way you can start tpm2-abrmd?
If not you'll need to run `tpm2_flushcontext -t` between commands.
@idesai we should probably add this support into the tools as well....

**Comment by rkgfk** [comment]
As I said I am running Fedora inside docker. So no chance to get tpm2-abrmd running. It won't start because of the missing dbus.
Flushing the context worked for that special case. But what do I do if I have a command-chain like in the use of the tpm2-pkcs11-tool when running `tpm2_ptool addtoken --pid=2 --label=my-ssh-token --sopin=yyy --userpin=xxx`.
This will stop working with the same error. But I don't have the chance to get between the commands, right?

**Comment by williamcroberts** [comment]
I see you have opened two bugs related to this, one for tpm2-pkcs11 and one for tpm2-tools. You're question on tpm2_ptool should be directed to the tpm2-pkcs11 bug (https://github.com/tpm2-software/tpm2-pkcs11/issues/758).

As far as running tpm2-abrmd inside of a docker container, we do it for all of our CI testing. dbus-run-session is your friend (see example below). It'll get you a session bus and you can set up the tcti options to connect to the session bus over the default system bus. I usually just launch a bash shell (these commands are from my docker container):

```bash
# you can use swtpm as well
tpm_server
dbus-run-session bash
tpm2-abrmd --allow-root --session --tcti=mssim &
./tools/tpm2 getrandom --tcti=tabrmd:bus_type=session --hex 4
7e0a8e03
```

**Comment by rkgfk** [comment]
Hmmm. This does not seem to help...
```
[root@cbd4e0d71202 /]# tpm2-abrmd --session --allow-root --tcti=swtpm --logger=stdout &
[1] 31763
[root@cbd4e0d71202 /]# 
** (process:31763): WARNING **: 16:04:08.048: tcti_conf before: "(null)"

** (tpm2-abrmd:31763): WARNING **: 16:04:08.048: tcti_conf after: "swtpm"

[root@cbd4e0d71202 /]# tpm2_ptool addtoken --pid=1 --label=my-ssh-token --sopin=123456 --userpin=123456
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/tpm2_pkcs11/tpm2_ptool.py", line 30, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/tpm2_pkcs11/tpm2_ptool.py", line 26, in main
    commandlet.init('A tool for manipulating the tpm2-pkcs11 database')
  File "/usr/lib/python3.10/site-packages/tpm2_pkcs11/command.py", line 102, in init
    commandlet.get()[d['which']](d)
  File "/usr/lib/python3.10/site-packages/tpm2_pkcs11/commandlets_token.py", line 313, in __call__
    AddTokenCommand.do_token_init(db, path, args)
  File "/usr/lib/python3.10/site-packages/tpm2_pkcs11/commandlets_token.py", line 254, in do_token_init
    usersealpriv, usersealpub, _ = tpm2.create(
  File "/usr/lib/python3.10/site-packages/tpm2_pkcs11/tpm2.py", line 226, in create
    raise RuntimeError("Could not execute tpm2_create: %s" %
RuntimeError: Could not execute tpm2_create: b'\n** (process:31773): CRITICAL **: 16:04:12.636: failed to allocate dbus proxy object: Could not connect: No such file or directory\nERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-tabrmd.so.0 \nERROR:tcti:src/tss2-tcti/tcti-device.c:442:Tss2_Tcti_Device_Init() Failed to open specified TCTI device file /dev/tpmrm0: No such file or directory \nERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0 \nERROR:tcti:src/tss2-tcti/tcti-device.c:442:Tss2_Tcti_Device_Init() Failed to open specified TCTI device file /dev/tpm0: No such file or directory \nERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0 \nWARNING:esys:src/tss2-esys/api/Esys_Create.c:398:Esys_Create_Finish() Received TPM Error \nERROR:esys:src/tss2-esys/api/Esys_Create.c:134:Esys_Create() Esys Finish ErrorCode (0x00000902) \nERROR: Esys_Create(0x902) - tpm:warn(2.0): out of memory for object contexts\nERROR: Unable to run tpm2_create\n'
[root@cbd4e0d71202 /]# 
```

**Comment by idesai** [comment]
> Ahh no RM. Any way you can start tpm2-abrmd?
> If not you'll need to run `tpm2_flushcontext -t` between commands.
> @idesai we should probably add this support into the tools as well....

As in, detect the tcti we are on--> Read the handle count on the TPM --> Flush?
Question is how we know what is safe to flush?
