### ISSUE TITLE
Segmentation fault on cross compiled binaries

### ISSUE THREAD

**Issue by yunusemreayhan** [tpm2-software/tpm2-tools#741]
### TARGET DEVICE FAILED RUN TRIAL 
```
[root@jibe-eek bin]# which tpm2_startup 
/usr/bin/tpm2_startup
[root@jibe-eek bin]# tpm2_startup 
Segmentation fault
[root@jibe-eek bin]# dmesg 
[  111.650000] Flags: nzCv  IRQs on  FIQs on  Mode USER_32  ISA ARM  Segment user
[  111.660000] Control: 0005317f  Table: 7732c000  DAC: 00000015
[  576.410000] tpm2_startup: unhandled page fault (11) at 0x000000c8, code 0x005
[  576.420000] pgd = c7318000
[  576.430000] [000000c8] *pgd=00000000
[  576.440000] 
[  576.460000] Pid: 798, comm:         tpm2_startup
[  576.460000] CPU: 0    Not tainted  (2.6.36.4-3-b1dev-maxim-jibe-b1-00002-g3eb538ee8b3 #19)
[  576.470000] PC is at 0x2a0017a4
[  576.490000] LR is at 0x40317978
[  576.510000] pc : [<2a0017a4>]    lr : [<40317978>]    psr: 20000010
[  576.510000] sp : bedd0b08  ip : 40325f20  fp : 00000000
[  576.520000] r10: 2a0011ac  r9 : 2a001798  r8 : 00000001
[  576.540000] r7 : 0000d750  r6 : bedd0ba4  r5 : 40325ec8  r4 : bedd0c7c
[  576.560000] r3 : 000000c8  r2 : bedd0bac  r1 : bedd0ba4  r0 : 00000001
[  576.560000] Flags: nzCv  IRQs on  FIQs on  Mode USER_32  ISA ARM  Segment user
[  576.570000] Control: 0005317f  Table: 77318000  DAC: 00000015
[root@jibe-eek bin]# ldd tpm2_startup 
	libsapi.so.0 => /usr/lib/libsapi.so.0 (0x40218000)
	libtcti-socket.so.0 => /usr/lib/libtcti-socket.so.0 (0x4009e000)
	libmarshal.so.0 => /usr/lib/libmarshal.so.0 (0x4016e000)
	libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0x4023b000)
	libc.so.0 => /lib/libc.so.0 (0x40195000)
	ld-uClibc.so.0 => /lib/ld-uClibc.so.0 (0x40057000)
	libdl.so.0 => /lib/libdl.so.0 (0x40151000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x401f6000)
```
### Configure flags
```
DISTCHECK_CONFIGURE_FLAGS =  'ac_cv_lbl_unaligned_fail=yes' 'ac_cv_func_mmap_fixed_mapped=yes' 'ac_cv_func_memcmp_working=yes' 'ac_cv_have_decl_malloc=yes' 'gl_cv_func_malloc_0_nonnull=yes' 'ac_cv_func_malloc_0_nonnull=yes' 'ac_cv_func_calloc_0_nonnull=yes' 'ac_cv_func_realloc_0_nonnull=yes' 'ac_cv_c_bigendian=no' 'PATH=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/bin:/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/usr/bin:/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/usr/sbin/:/home/change/maxim-ic/lde-3.0/.lde/bin:/home/change/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/:/home/change/bin/:/home/change/CodeSourcery/Sourcery_G++_Lite/bin' 'AR=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-ar' 'AS=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-as' 'LD=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-ld --sysroot=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging' 'NM=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-nm' 'CC=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-gcc --sysroot=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging' 'GCC=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-gcc --sysroot=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging' 'CPP=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-cpp --sysroot=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging' 'CXX=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-g++ --sysroot=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging' 'FC=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-gfortran --sysroot=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging' 'RANLIB=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-ranlib' 'STRIP=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-strip' 'OBJCOPY=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-objcopy' 'OBJDUMP=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-objdump' 'AR_FOR_BUILD=/usr/bin/ar' 'AS_FOR_BUILD=/usr/bin/as' 'CC_FOR_BUILD=/usr/bin/gcc' 'GCC_FOR_BUILD=/usr/bin/gcc' 'CXX_FOR_BUILD=/usr/bin/g++' 'FC_FOR_BUILD=/usr/bin/ld' 'LD_FOR_BUILD=/usr/bin/ld' 'CFLAGS_FOR_BUILD=-O2 -I/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/include -I/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/usr/include' 'CXXFLAGS_FOR_BUILD=-I/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/include -I/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/usr/include' 'LDFLAGS_FOR_BUILD=-L/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/lib -L/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/usr/lib -Wl,-rpath,/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/usr/lib' 'FCFLAGS_FOR_BUILD=' 'DEFAULT_ASSEMBLER=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-as' 'DEFAULT_LINKER=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-ld --sysroot=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging' 'CFLAGS=-pipe -Os  -mtune=arm926ej-s -march=armv5te -mabi=aapcs-linux -msoft-float -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/include -I/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/include' 'CXXFLAGS=-pipe -Os  -mtune=arm926ej-s -march=armv5te -mabi=aapcs-linux -msoft-float -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/include -I/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/include' 'LDFLAGS=-L/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/lib -L/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/lib' 'FCFLAGS=' 'PKG_CONFIG_SYSROOT_DIR=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging' 'PKG_CONFIG=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/usr/bin/pkg-config' 'PKG_CONFIG_PATH=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/lib/pkgconfig:' 'PERLLIB=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/usr/lib/perl' 'STAGING_DIR=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging' '--prefix=/usr' '--build=i686-pc-linux-gnu' '--target=arm-linux' '--host=arm-linux' 'build_alias=i686-pc-linux-gnu' 'host_alias=arm-linux' 'target_alias=arm-linux'
 
```
### Buildroot configuration for tpm-tss
```
define TPMTSS_CONFIGURE_CMDS
	(cd $(@D);\
		rm -rf config.cache;\
		./bootstrap;\
		${CONFIGURE_FILE_ERRORS_PATCHS} \
		./configure \
		$(TARGET_CONFIGURE_ARGS) \
		$(TARGET_CONFIGURE_OPTS) \
		--prefix=/usr \
		--build=${GNU_HOST_NAME} \
		--target=${GNU_TARGET_NAME} \
		--host=${GNU_TARGET_NAME}; \
	)
endef
```
### Buildroot configuration for tpm-tools
```
define TPMTSSTOOLS_CONFIGURE_CMDS
	(cd $(@D); \
		rm -rf config.cache; \
		mkdir -p m4; \
		./bootstrap; \
		./configure \
		$(TARGET_CONFIGURE_ARGS) \
		$(TARGET_CONFIGURE_OPTS) \
		--prefix=/usr \
		--build=${GNU_HOST_NAME} \
		--target=${GNU_TARGET_NAME} \
		--host=${GNU_TARGET_NAME}
		--with-tcti-socket=yes \
		--with-tcti-tabrmd=no \
		--with-tcti-device=no; \
	)
endef
```
The reason may be caused by my build configuration, but any idea about the segmentation fault?
Thanks in advance...

**Comment by williamcroberts** [comment]
FSR code is 0x05, wich is invalid translation for whatever thats worth: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0198e/I1039321.html

That pointer looks like garbage: 0x000000c8

Can you build with debugging symbols and run addr2line?

**Comment by yunusemreayhan** [comment]
compiled with -ggdb3 -O0
```
(gdb) target remote 192.168.20.77:1010 ./tpm2_startup
Remote debugging using 192.168.20.77:1010 ./tpm2_startup
[New Thread 744]
(no debugging symbols found)
0x40067930 in _start () from /home/change/maxim-ic/lde-3.0/TREE/user/buildroot/target/lib/ld-uClibc.so.0
(gdb) 
```
Does this mean some thing?

**Comment by williamcroberts** [comment]
For debug symbols just set CFLAGS=-g
```
./bootstrap
./configure CFLAGS=-g
make
```

**Comment by yunusemreayhan** [comment]
```
(gdb) target remote 192.168.20.77:1010
Remote debugging using 192.168.20.77:1010
[New Thread 779]
(no debugging symbols found)
0x400c5930 in _start () from /home/change/maxim-ic/lde-3.0/TREE/user/buildroot/target/lib/ld-uClibc.so.0
(gdb) bt
#0  0x400c5930 in _start () from /home/change/maxim-ic/lde-3.0/TREE/user/buildroot/target/lib/ld-uClibc.so.0
#1  0x00000000 in ?? ()
(gdb) continue 
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x2a0017a4 in ?? ()
(gdb) bt
#0  0x2a0017a4 in ?? ()
Cannot access memory at address 0x0
(gdb) 
```

That flag did not changed the result, this is how i called configure

```
		./configure \
		CFLAGS=-g \
		$(TARGET_CONFIGURE_ARGS) \
		$(TARGET_CONFIGURE_OPTS) \
		--build=${GNU_HOST_NAME} \
		--host=${GNU_TARGET_NAME}; \
```

and this is : 

```
./configure CFLAGS=-g ac_cv_lbl_unaligned_fail=yes ac_cv_func_mmap_fixed_mapped=yes ac_cv_func_memcmp_working=yes ac_cv_have_decl_malloc=yes gl_cv_func_malloc_0_nonnull=yes ac_cv_func_malloc_0_nonnull=yes ac_cv_func_calloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes ac_cv_c_bigendian=no PATH="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/bin:/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/usr/bin:/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/usr/sbin/:/home/change/maxim-ic/lde-3.0/.lde/bin:/home/change/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/:/home/change/bin/:/home/change/CodeSourcery/Sourcery_G++_Lite/bin" AR="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-ar" AS="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-as" LD="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-ld --sysroot=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging" NM="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-nm" CC="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-gcc --sysroot=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging" GCC="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-gcc --sysroot=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging" CPP="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-cpp --sysroot=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging" CXX="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-g++ --sysroot=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging" FC="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-gfortran --sysroot=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging" RANLIB="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-ranlib" STRIP="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-strip" OBJCOPY="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-objcopy" OBJDUMP="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-objdump" AR_FOR_BUILD="/usr/bin/ar" AS_FOR_BUILD="/usr/bin/as" CC_FOR_BUILD="/usr/bin/gcc" GCC_FOR_BUILD="/usr/bin/gcc" CXX_FOR_BUILD="/usr/bin/g++" FC_FOR_BUILD="/usr/bin/ld" LD_FOR_BUILD="/usr/bin/ld" CFLAGS_FOR_BUILD="-O2 -I/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/include -I/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/usr/include" CXXFLAGS_FOR_BUILD="-I/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/include -I/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/usr/include" LDFLAGS_FOR_BUILD="-L/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/lib -L/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/usr/lib -Wl,-rpath,/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/usr/lib" FCFLAGS_FOR_BUILD="" DEFAULT_ASSEMBLER="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-as" DEFAULT_LINKER="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/bin/arm-unknown-linux-uclibcgnueabi-ld --sysroot=/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging" CFLAGS="-pipe -Os  -mtune=arm926ej-s -march=armv5te -mabi=aapcs-linux -msoft-float -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/include -I/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/include" CXXFLAGS="-pipe -Os  -mtune=arm926ej-s -march=armv5te -mabi=aapcs-linux -msoft-float -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/include -I/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/include" LDFLAGS="-L/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/lib -L/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/lib" FCFLAGS="" PKG_CONFIG_SYSROOT_DIR="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging" PKG_CONFIG="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/usr/bin/pkg-config" PKG_CONFIG_PATH="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging/usr/lib/pkgconfig:" PERLLIB="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/host/usr/lib/perl" STAGING_DIR="/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/staging" --build=i686-pc-linux-gnu --host=arm-linux; 
```
Could we figure out this. I am stacked,
Thx.

**Comment by williamcroberts** [comment]
I'm not sure off hand why -g is not providing debug symbols.  I would start by tracing it with printf statements and narrowing down where it crashes. Look like a NULL deref considering "Cannot access memory at address 0x0"
